import pygame


# window information
WINDOW_WIDTH, WINDOW_HEIGHT = 1200, 800
GRAPH_WIDTH, GRAPH_HEIGHT = (3 * WINDOW_WIDTH) // 4, WINDOW_HEIGHT
CONTROL_WIDTH, CONTROL_HEIGHT = WINDOW_WIDTH // 4, WINDOW_HEIGHT

# button information
BUTTON_WIDTH, BUTTON_HEIGHT = 150, 100
GEN_BTN_X = SORT_BTN_X = RESET_BTN_X = GRAPH_WIDTH + (CONTROL_WIDTH // 2) - (BUTTON_WIDTH // 2)
GEN_BTN_Y = 100
SORT_BTN_Y = 250
RESET_BTN_Y = 400
TYPE_GEN = 'Generate'
TYPE_SORT = 'Sort'
TYPE_RESET = 'Reset'

# sorting algorithm types
TYPE_INSERTION = 'insertion'
TYPE_QUICKSORT = 'quicksort'
TYPE_MERGESORT = 'mergesort'
TYPE_SELECTION = 'selection'

# graph information
PLOT_X, PLOT_Y = GRAPH_WIDTH // 20, GRAPH_HEIGHT // 20  # 5% buffer of total
PLOT_WIDTH, PLOT_HEIGHT = GRAPH_WIDTH - (2 * PLOT_X), WINDOW_HEIGHT - (2 * PLOT_Y)

# colours in rgb
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (160, 160, 160)
DARK_GRAY = (96, 96, 96)
DARKER_GRAY = (32, 32, 32)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)